### ISSUE TITLE
MetaMask: Two Aurora listed

### ISSUE THREAD

**Issue by traumanaked** [aurora-is-near/doc.aurora.dev#50]
1) When using Trisolaris this last month, Aurora gas fees went to one Aurora contract (#A) on MetaMask

2) When swapping or claiming Aurora tokens went to another Aurora contract (#B) on MetaMask

This resulted in #B accumulating a positive balance while #A remained at 0.00 due to no gas fees.

Recently, Trisolaris has charged Aurora gas fees to #A. This results in 'rejection' since it has no balance. Aurora #B continues to be the source contract to receive Aurora tokens, however I cannot claim or swap since Aurora #A cannot be 'charged' gas fees with no balance.

Help please?

**Comment by antonpaisov** [comment]
hey @traumanaked !
thanks for your report, I think it's more related to http://github.com/aurora-is-near/aurora-relayer 
and it should also be resolved by now, but if not, please report it there

thanks,
Anton
